### PR TITLE
fix: use DB record ID in session cookie (fixes #30)

### LINKED ISSUE #30: Session is not reused when calling store.Save without session ID
```
// Save session and set cookie header
func (st *Store) Save(r *http.Request, w http.ResponseWriter, session *sessions.Session) error {
	s, _ := context.Get(r, contextKey(session.Name())).(*gormSession)
...
	// set session id cookie
	id, err := securecookie.EncodeMulti(session.Name(), session.ID, st.Codecs...)
```

If a caller passes a valid session with `Name` set but `ID` unset, the cookie value will be empty and a new session created after the next call to `New()` instead of reusing the existing session.

The cookie should be set to the value of `s.ID` instead.

### PR DESCRIPTION
**Pull request by Benzhaomin**

### CODE REVIEW

**Comment by wader** [comment]
Hi, yes that is not good, thanks for fix and test case. Wonder if we should fix non-v2 also?

**Comment by Benzhaomin** [comment]
Right, same code so same fix in v1

**Comment by wader** [comment]
👍  was thinking about sharing code between them when i did v2 but not really worth i think

**Comment by wader** [comment]
Thanks!

**Pull request merged**
